services:
  db_accounts:
    build: ./db_container
    container_name: db_accounts
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "6132:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db_container/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    profiles:
      - dev
      - prod


  bot_and_fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot_and_fastapi
    volumes:
      - ./data/database.db:/data/database.db
    ports:
      - "8000:8000"
    restart: unless-stopped
    profiles:
      - prod


volumes:
  pg_data: